/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nano_ecc */

#ifndef _Included_nano_ecc
#define _Included_nano_ecc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nano_ecc
 * Method:    api_ecc_make_key
 * Signature: ([B[B[B[B)I
 */
JNIEXPORT jint JNICALL Java_nano_1ecc_api_1ecc_1make_1key
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
